# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('unitA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitA', to='units.Unit')),
                ('unitB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitB', to='units.Unit')),
            ],
        ),
    ]
