# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fights',
            name='vs1',
            field=models.FloatField(verbose_name='Pikinier'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs10',
            field=models.FloatField(verbose_name='Kap\u0142an'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs100',
            field=models.FloatField(verbose_name='Gnoll maruder'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs101',
            field=models.FloatField(verbose_name='Jaszczurocz\u0142ek'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs102',
            field=models.FloatField(verbose_name='Reptilion'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs103',
            field=models.FloatField(verbose_name='Gorgona'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs104',
            field=models.FloatField(verbose_name='Wielka gorgona'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs105',
            field=models.FloatField(verbose_name='Wa\u017cka'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs106',
            field=models.FloatField(verbose_name='Smocza wa\u017cka'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs107',
            field=models.FloatField(verbose_name='Bazyliszek'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs108',
            field=models.FloatField(verbose_name='Bazyliszek wi\u0119kszy'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs109',
            field=models.FloatField(verbose_name='Wiwerna'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs11',
            field=models.FloatField(verbose_name='Kawalerzysta'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs110',
            field=models.FloatField(verbose_name='Wiwerna kr\xf3lewska'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs111',
            field=models.FloatField(verbose_name='Hydra'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs112',
            field=models.FloatField(verbose_name='Hydra chaosu'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs113',
            field=models.FloatField(verbose_name='Nimfa'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs114',
            field=models.FloatField(verbose_name='Rusa\u0142ka'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs115',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak powietrza'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs116',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak burzy'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs117',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak wody'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs118',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak lodu'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs119',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak ognia'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs12',
            field=models.FloatField(verbose_name='Czempion'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs120',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak energii'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs121',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak ziemi'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs122',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak magmy'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs123',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak umys\u0142u'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs124',
            field=models.FloatField(verbose_name='\u017bywio\u0142ak magii'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs125',
            field=models.FloatField(verbose_name='Ognisty ptak'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs126',
            field=models.FloatField(verbose_name='Feniks'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs127',
            field=models.FloatField(verbose_name='Ch\u0142op'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs128',
            field=models.FloatField(verbose_name='Nizio\u0142ek'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs129',
            field=models.FloatField(verbose_name='Rozb\xf3jnik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs13',
            field=models.FloatField(verbose_name='Anio\u0142'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs130',
            field=models.FloatField(verbose_name='Knurzy je\u017adziec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs131',
            field=models.FloatField(verbose_name='Mumia'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs132',
            field=models.FloatField(verbose_name='Nomad'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs133',
            field=models.FloatField(verbose_name='Strzelec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs134',
            field=models.FloatField(verbose_name='Troll'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs135',
            field=models.FloatField(verbose_name='Z\u0142oty golem'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs136',
            field=models.FloatField(verbose_name='Diamentowy golem'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs137',
            field=models.FloatField(verbose_name='Czarodziej'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs138',
            field=models.FloatField(verbose_name='Czarodziejski smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs139',
            field=models.FloatField(verbose_name='Rdzawy smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs14',
            field=models.FloatField(verbose_name='Archanio\u0142'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs140',
            field=models.FloatField(verbose_name='Kryszta\u0142owy smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs141',
            field=models.FloatField(verbose_name='B\u0142\u0119kitny smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs15',
            field=models.FloatField(verbose_name='Centaur'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs16',
            field=models.FloatField(verbose_name='Centaur bojowy'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs17',
            field=models.FloatField(verbose_name='Krasnolud'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs18',
            field=models.FloatField(verbose_name='Krasnoludzki wojownik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs19',
            field=models.FloatField(verbose_name='Le\u015bny elf'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs2',
            field=models.FloatField(verbose_name='Halabardnik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs20',
            field=models.FloatField(verbose_name='Wysoki elf'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs21',
            field=models.FloatField(verbose_name='Pegaz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs22',
            field=models.FloatField(verbose_name='Srebrny pegaz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs23',
            field=models.FloatField(verbose_name='Drzewiec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs24',
            field=models.FloatField(verbose_name='Ent'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs25',
            field=models.FloatField(verbose_name='Jednoro\u017cec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs26',
            field=models.FloatField(verbose_name='Jednoro\u017cec bitewny'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs27',
            field=models.FloatField(verbose_name='Zielony smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs28',
            field=models.FloatField(verbose_name='Z\u0142oty smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs29',
            field=models.FloatField(verbose_name='Gremlin'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs3',
            field=models.FloatField(verbose_name='\u0141ucznik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs30',
            field=models.FloatField(verbose_name='Wi\u0119kszy gremlin'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs31',
            field=models.FloatField(verbose_name='Kamienny gargulec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs32',
            field=models.FloatField(verbose_name='Obsydianowy gargulec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs33',
            field=models.FloatField(verbose_name='Kamienny golem'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs34',
            field=models.FloatField(verbose_name='\u017belazny golem'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs35',
            field=models.FloatField(verbose_name='Mag'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs36',
            field=models.FloatField(verbose_name='Arcymag'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs37',
            field=models.FloatField(verbose_name='D\u017cinn'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs38',
            field=models.FloatField(verbose_name='Wielki d\u017cinn'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs39',
            field=models.FloatField(verbose_name='Naga'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs4',
            field=models.FloatField(verbose_name='Kusznik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs40',
            field=models.FloatField(verbose_name='Kr\xf3lewska naga'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs41',
            field=models.FloatField(verbose_name='Gigant'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs42',
            field=models.FloatField(verbose_name='Tytan'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs43',
            field=models.FloatField(verbose_name='Chochlik'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs44',
            field=models.FloatField(verbose_name='Chowaniec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs45',
            field=models.FloatField(verbose_name='Gog'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs46',
            field=models.FloatField(verbose_name='Magog'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs47',
            field=models.FloatField(verbose_name='Piekielny ogar'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs48',
            field=models.FloatField(verbose_name='Cerber'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs49',
            field=models.FloatField(verbose_name='Demon'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs5',
            field=models.FloatField(verbose_name='Gryf'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs50',
            field=models.FloatField(verbose_name='Rogaty demon'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs51',
            field=models.FloatField(verbose_name='Czart'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs52',
            field=models.FloatField(verbose_name='Czarci lord'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs53',
            field=models.FloatField(verbose_name='Ifryt'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs54',
            field=models.FloatField(verbose_name='Su\u0142ta\u0144ski ifryt'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs55',
            field=models.FloatField(verbose_name='Diabe\u0142'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs56',
            field=models.FloatField(verbose_name='Arcydiabe\u0142'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs57',
            field=models.FloatField(verbose_name='Szkielet'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs58',
            field=models.FloatField(verbose_name='Ko\u015bciej'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs59',
            field=models.FloatField(verbose_name='O\u017cywieniec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs6',
            field=models.FloatField(verbose_name='Gryf kr\xf3lewski'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs60',
            field=models.FloatField(verbose_name='Zombie'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs61',
            field=models.FloatField(verbose_name='Zjawa'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs62',
            field=models.FloatField(verbose_name='Upi\xf3r'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs63',
            field=models.FloatField(verbose_name='Wampir'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs64',
            field=models.FloatField(verbose_name='Wampirzy lord'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs65',
            field=models.FloatField(verbose_name='Lisz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs66',
            field=models.FloatField(verbose_name='Arcylisz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs67',
            field=models.FloatField(verbose_name='Czarny rycerz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs68',
            field=models.FloatField(verbose_name='Upiorny rycerz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs69',
            field=models.FloatField(verbose_name='Ko\u015bciany smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs7',
            field=models.FloatField(verbose_name='Zbrojny'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs70',
            field=models.FloatField(verbose_name='Upiorny smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs71',
            field=models.FloatField(verbose_name='Troglodyta'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs72',
            field=models.FloatField(verbose_name='Piekielny troglodyta'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs73',
            field=models.FloatField(verbose_name='Harpia'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs74',
            field=models.FloatField(verbose_name='Harpia wied\u017ama'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs75',
            field=models.FloatField(verbose_name='Z\u0142e oko'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs76',
            field=models.FloatField(verbose_name='Obserwator'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs77',
            field=models.FloatField(verbose_name='Meduza'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs78',
            field=models.FloatField(verbose_name='Meduza kr\xf3lewska'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs79',
            field=models.FloatField(verbose_name='Minotaur'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs8',
            field=models.FloatField(verbose_name='Krzy\u017cowiec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs80',
            field=models.FloatField(verbose_name='Wielki minotaur'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs81',
            field=models.FloatField(verbose_name='Mantikora'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs82',
            field=models.FloatField(verbose_name='Chimera'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs83',
            field=models.FloatField(verbose_name='Czerwony smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs84',
            field=models.FloatField(verbose_name='Czarny smok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs85',
            field=models.FloatField(verbose_name='Goblin'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs86',
            field=models.FloatField(verbose_name='Hobgoblin'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs87',
            field=models.FloatField(verbose_name='Wilczy je\u017adziec'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs88',
            field=models.FloatField(verbose_name='Wilczy rycerz'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs89',
            field=models.FloatField(verbose_name='Ork'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs9',
            field=models.FloatField(verbose_name='Mnich'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs90',
            field=models.FloatField(verbose_name='Uruk'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs91',
            field=models.FloatField(verbose_name='Ogr'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs92',
            field=models.FloatField(verbose_name='Ogr szaman'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs93',
            field=models.FloatField(verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs94',
            field=models.FloatField(verbose_name='Ptak gromu'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs95',
            field=models.FloatField(verbose_name='Cyklop'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs96',
            field=models.FloatField(verbose_name='Cyklop kr\xf3lewski'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs97',
            field=models.FloatField(verbose_name='Behemot'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs98',
            field=models.FloatField(verbose_name='Staro\u017cytny behemot'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='vs99',
            field=models.FloatField(verbose_name='Gnoll'),
        ),
    ]
