# Generated by Django 2.0 on 2017-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fights',
            name='vs23',
            field=models.FloatField(verbose_name='Dendroid Guard'),
        ),
    ]
