# Generated by Django 2.0 on 2018-01-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('plural', models.CharField(max_length=35)),
                ('gold_cost', models.IntegerField(verbose_name='Gold')),
                ('fight_value', models.IntegerField()),
                ('ai_value', models.IntegerField(verbose_name='AI Value')),
                ('growth', models.IntegerField()),
                ('horde_growth', models.IntegerField()),
                ('hp', models.IntegerField(verbose_name='HP')),
                ('speed', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('min_dmg', models.IntegerField()),
                ('max_dmg', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('spells', models.IntegerField()),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('upgraded', models.BooleanField(default=False, verbose_name='Upgraded?')),
                ('b_double_wide', models.BooleanField(default=False, verbose_name='Big?')),
                ('b_free_attack', models.BooleanField(default=False, verbose_name='No retaliation?')),
                ('b_no_melee_pen', models.BooleanField(default=False, verbose_name='No melee penalty?')),
                ('b_two_attacks', models.BooleanField(default=False, verbose_name='Two attacks?')),
                ('b_undead', models.BooleanField(default=False, verbose_name='Undead?')),
                ('b_elemental', models.BooleanField(default=False, verbose_name='Elemental?')),
                ('b_golem', models.BooleanField(default=False, verbose_name='Golem?')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Town')),
            ],
        ),
    ]
