# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gold_cost', models.IntegerField()),
                ('fight_value', models.IntegerField()),
                ('ai_value', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('horde_growth', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('min_dmg', models.IntegerField()),
                ('max_dmg', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('spells', models.IntegerField()),
                ('b_double_wide', models.BooleanField(default=False)),
                ('b_free_attack', models.BooleanField(default=False)),
                ('b_no_melee_pen', models.BooleanField(default=False)),
                ('b_two_attacks', models.BooleanField(default=False)),
                ('b_undead', models.BooleanField(default=False)),
                ('b_elemental', models.BooleanField(default=False)),
                ('b_golem', models.BooleanField(default=False)),
            ],
        ),
    ]
