# Generated by Django 2.0 on 2018-01-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='upgraded',
            new_name='b_upgraded',
        ),
    ]
