# Generated by Django 2.0 on 2017-12-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='town',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='units.Town'),
        ),
    ]
