# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='upgraded',
            field=models.BooleanField(default=False, verbose_name='Upgraded?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ai_value',
            field=models.IntegerField(verbose_name='AI Value'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_double_wide',
            field=models.BooleanField(default=False, verbose_name='Big?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_elemental',
            field=models.BooleanField(default=False, verbose_name='Elemental?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_free_attack',
            field=models.BooleanField(default=False, verbose_name='No retaliation?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_golem',
            field=models.BooleanField(default=False, verbose_name='Golem?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_no_melee_pen',
            field=models.BooleanField(default=False, verbose_name='No melee penalty?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_two_attacks',
            field=models.BooleanField(default=False, verbose_name='Two attacks?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='b_undead',
            field=models.BooleanField(default=False, verbose_name='Undead?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='gold_cost',
            field=models.IntegerField(verbose_name='Gold'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='hp',
            field=models.IntegerField(verbose_name='HP'),
        ),
        migrations.AddField(
            model_name='unit',
            name='town',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='units.Town'),
            preserve_default=False,
        ),
    ]
