# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20170212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='town',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='units.Town'),
        ),
    ]
