names = [
    'Pikeman',
    'Halberdier',
    'Archer',
    'Marksman',
    'Griffin',
    'Royal Griffin',
    'Swordsman',
    'Crusader',
    'Monk',
    'Zealot',
    'Cavalier',
    'Champion',
    'Angel',
    'Archangel',
    'Centaur',
    'Centaur Captain',
    'Dwarf',
    'Battle Dwarf',
    'Wood Elf',
    'Grand Elf',
    'Pegasus',
    'Silver Pegasus',
    'Dendroid Guard',
    'Dendroid Soldier',
    'Unicorn',
    'War Unicorn',
    'Green Dragon',
    'Gold Dragon',
    'Gremlin',
    'Master Gremlin',
    'Stone Gargoyle',
    'Obsidian Gargoyle',
    'Stone Golem',
    'Iron Golem',
    'Mage',
    'Arch Mage',
    'Genie',
    'Master Genie',
    'Naga',
    'Naga Queen',
    'Giant',
    'Titan',
    'Imp',
    'Familiar',
    'Gog',
    'Magog',
    'Hell Hound',
    'Cerberus',
    'Demon',
    'Horned Demon',
    'Pit Fiend',
    'Pit Lord',
    'Efreet',
    'Efreet Sultan',
    'Devil',
    'Arch Devil',
    'Skeleton',
    'Skeleton Warrior',
    'Walking Dead',
    'Zombie',
    'Wight',
    'Wraith',
    'Vampire',
    'Vampire Lord',
    'Lich',
    'Power Lich',
    'Black Knight',
    'Dread Knight',
    'Bone Dragon',
    'Ghost Dragon',
    'Troglodyte',
    'Infernal Troglodyte',
    'Harpy',
    'Harpy Hag',
    'Beholder',
    'Evil Eye',
    'Medusa',
    'Medusa Queen',
    'Minotaur',
    'Minotaur King',
    'Manticore',
    'Scorpicore',
    'Red Dragon',
    'Black Dragon',
    'Goblin',
    'Hobgoblin',
    'Wolf Rider',
    'Wolf Raider',
    'Orc',
    'Orc Chieftain',
    'Ogre',
    'Ogre Mage',
    'Roc',
    'Thunderbird',
    'Cyclops',
    'Cyclops King',
    'Behemoth',
    'Ancient Behemoth',
    'Gnoll',
    'Gnoll Marauder',
    'Lizardman',
    'Lizard Warrior',
    'Serpent Fly',
    'Dragon Fly',
    'Basilisk',
    'Greater Basilisk',
    'Gorgon',
    'Mighty Gorgon',
    'Wyvern',
    'Wyvern Monarch',
    'Hydra',
    'Chaos Hydra',
    'Pixie',
    'Sprite',
    'Air Elemental',
    'Storm Elemental',
    'Water Elemental',
    'Ice Elemental',
    'Fire Elemental',
    'Energy Elemental',
    'Earth Elemental',
    'Magma Elemental',
    'Psychic Elemental',
    'Magic Elemental',
    'Firebird',
    'Phoenix',
    'Peasant',
    'Halfling',
    'Rogue',
    'Boar',
    'Mummy',
    'Nomad',
    'Sharpshooter',
    'Troll',
    'Gold Golem',
    'Diamond Golem',
    'Enchanter',
    'Faerie Dragon',
    'Rust Dragon',
    'Crystal Dragon',
    'Azure Dragon'
]
